#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

docker build --pull --no-cache \
       --build-arg BASE_VERSION=$TAG_BASE_BRANCH \
       --tag $TAG_SHA \
       -f docker/Dockerfile \
       $HERE

# We always push the SHA tagged versions, for debugging if the tests
# after this step fail
docker push $TAG_SHA
