#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

# In case we switch agents between steps
[ ! -z $(docker images -q $TAG_SHA) ] || docker pull $TAG_SHA

USER_UID=`id -u`
USER_GID=`id -g`
USER_STR="${USER_UID}:${USER_GID}"

if [ -f $PACKAGE_ROOT/.ssh/id_rsa ]; then
    echo "Using deploy key"
    PATH_SSH=$PACKAGE_ROOT/.ssh
else
    echo "Using personal key"
    PATH_SSH=$HOME/.ssh
fi

docker run --rm \
        -u $USER_STR \
        -v $PACKAGE_ROOT:/orderly \
        -v $PATH_SSH:/root/.ssh:ro
        -w /orderly \
        --entrypoint /orderly/publish.sh \
        $TAG_SHA
