#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
ROOT=$(realpath $HERE/..)

export VAULT_ADDR="https://$(hostname):8200"
export VAULT_TOKEN=$(vault login -method=github -token-only)

if [ -f $ROOT/.ssh/production/id_rsa ]; then
    echo "production deploy key already exists"
else
    mkdir -p $ROOT/.ssh/production
    vault read -field key \
          secret/ncov/deploy-keys/mrc-ide/global-lmic-reports > \
          $ROOT/.ssh/production/id_rsa
    chmod 600 $ROOT/.ssh/production/id_rsa
    vault read -field pub \
          secret/ncov/deploy-keys/mrc-ide/global-lmic-reports > \
          $ROOT/.ssh/production/id_rsa.pub
fi

if [ -f $ROOT/.ssh/staging/id_rsa ]; then
    echo "staging deploy key already exists"
else
    mkdir -p $ROOT/.ssh/staging
    vault read -field key \
          secret/ncov/deploy-keys/mrc-ide/global-lmic-reports-staging > \
          $ROOT/.ssh/staging/id_rsa
    chmod 600 $ROOT/.ssh/staging/id_rsa
    vault read -field pub \
          secret/ncov/deploy-keys/mrc-ide/global-lmic-reports-staging > \
          $ROOT/.ssh/staging/id_rsa.pub
fi

if [ -f $ROOT/.ssh/results/id_rsa ]; then
    echo "results deploy key already exists"
else
    mkdir -p $ROOT/.ssh/results
    vault read -field key \
          secret/ncov/deploy-keys/mrc-ide/global-lmic-results > \
          $ROOT/.ssh/results/id_rsa
    chmod 600 $ROOT/.ssh/results/id_rsa
    vault read -field pub \
          secret/ncov/deploy-keys/mrc-ide/global-lmic-results > \
          $ROOT/.ssh/results/id_rsa.pub
fi
