#!/usr/bin/env bash
set -e
DOCS_DIR=gh-meffs
VERSION=$(git rev-parse --short HEAD)
REMOTE_URL=git@github.com:mrc-ide/global-lmic-meffs.git

TODAY=$(date "+%Y-%m-%d")
DATE=${1:-$TODAY}

export GIT_SSH_COMMAND="ssh -i ../.ssh/meffs/id_rsa"

git -C ${DOCS_DIR} config user.email "oj.watson@hotmail.co.uk"
git -C ${DOCS_DIR} config user.name "OJWatson"

if [ ! -d "${DOCS_DIR}/.git" ]; then
    git init ${DOCS_DIR}
    echo "init again"
    git -C ${DOCS_DIR} add .
    git -C ${DOCS_DIR} commit --no-verify -m "Update server results for ${DATE} at version ${VERSION} "
    git -C ${DOCS_DIR} remote add origin ${REMOTE_URL}
    git -C ${DOCS_DIR} push --force -u origin master
else 
    git -C ${DOCS_DIR} pull
    echo "pull"
    git -C ${DOCS_DIR} add .
    git -C ${DOCS_DIR} commit --no-verify -m "Update server results for ${DATE} at version ${VERSION} "
    #git -C ${DOCS_DIR} remote add origin ${REMOTE_URL}
    git -C ${DOCS_DIR} push
fi


