#!/usr/bin/env bash
set -e
DOCS_DIR=gh-pages
VERSION=$(git rev-parse --short HEAD)

WHERE=$1

if [[ $WHERE == "staging" ]]; then
    echo "Pushing to staging not supported using this script. See documentation"
    exit 1
elif [[ $WHERE == "production" ]]; then
    REMOTE_URL=git@github.com:mrc-ide/global-lmic-reports.git
else
    echo "Usage: ./publish_website.sh staging|production"
    exit 1
fi

if [ -f .ssh/$WHERE/id_rsa ]; then
    echo "Using deploy key"
    ## NOTE, uses one directory above the root
    export GIT_SSH_COMMAND="ssh -i ../.ssh/$WHERE/id_rsa"
fi


if [ -z $(git -C ${DOCS_DIR} config --get user.email) ]; then
    git -C ${DOCS_DIR} config user.email "oj.watson@hotmail.co.uk"
    git -C ${DOCS_DIR} config user.name "OJWatson"
fi

git -C ${DOCS_DIR} add data
git -C ${DOCS_DIR} commit --no-verify -m "Add data for version ${VERSION}"
git -C ${DOCS_DIR} push --force -u origin master
git -C ${DOCS_DIR} add .
git -C ${DOCS_DIR} commit --no-verify -m "Update pages for version ${VERSION}"
git -C ${DOCS_DIR} push --force -u origin master
